project:
  type: website #specifies as a website
  output-dir: docs #output directory saved while rendering
  render: 
    - "*.qmd" #render all files with a .qmd

website:
  title: "Rachael Olson" #title displayed on the website
  navbar: #navigation bar settings
    left:
      - href: index.qmd #qmd file for the home page
        text: Home #title name on the navigation bar 
      - href: Interactive_Mini_Project_One_Olson.qmd 
        text: Interactive Choropleth Maps
      - href: table_scrap_mini_project.qmd 
        text: Table Scraping Acquistion 
      - href: Mini_Project_4_Olson.qmd
        text: Text Analysis Techniques
        
#output formating      
format:
  html: 
    theme: materia
    css: styles.css #link to stylistic choices for font, coloring, and stylistic choices
    toc: true #table of contents page
